ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".kcdevops.online
CATALOGUE_HOST: catalogue-"{{ env }}".kcdevops.online
REDIS_HOST: redis-"{{ env }}".kcdevops.online
USER_HOST: user-"{{ env }}".kcdevops.online
CART_HOST: cart-"{{ env }}".kcdevops.online
MYSQL_HOST: mysql-"{{ env }}".kcdevops.online
SHIPPING_HOST: shipping-"{{ env }}".kcdevops.online
RABBITMQ_HOST: rabbitmq-"{{ env }}".kcdevops.online
PAYMENT_HOST: payment-"{{ env }}".kcdevops.online
FRONTEND_HOST: frontend-"{{ env }}".kcdevops.online