[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.kcdevops.online

[redis]
localhost

[user]
user-dev.kcdevops.online

[cart]
cart-dev.kcdevops.online

[mysql]
mysql-dev.kcdevops.online

[shipping]
shipping-dev.kcdevops.online

[rabbitmq]
rabbitmq-dev.kcdevops.online

[payment]
payment-dev.kcdevops.online

[frontend]
frontend-dev.kcdevops.online